=begin
Uber API

Move your app forward with the Uber API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ProductsController < ApplicationController

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
